name: android-emulator-rooted

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session hours'
        required: false
        default: '6'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo chmod 666 /dev/kvm

      - name: Install ADB
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y android-sdk-platform-tools

      - name: Free Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache
          sudo docker image prune --all --force

      - name: Setup FRP
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /tmp/frpc
          sudo chmod +x /tmp/frpc
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          [[proxies]]
          name = "adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          EOF
          nohup /tmp/frpc -c frpc.toml > frpc.log 2>&1 &

      - name: Run Android
        run: |
          adb kill-server || true
          docker pull budtmo/docker-android:emulator_11.0
          docker run -d --name android --privileged --device /dev/kvm -p 5555:5555 -e DEVICE="Samsung Galaxy S10" -e DATAPARTITION=8g -e CORES=4 -e RAM=8192 --cpus=4 --memory=12g budtmo/docker-android:emulator_11.0
          sleep 90
          adb connect 127.0.0.1:5555
          sleep 5
          DEVICE=$(adb devices | grep 5555 | awk '{print $1}')
          adb -s $DEVICE wait-for-device
          sleep 10
          adb -s $DEVICE shell 'cat > /data/local/tmp/su << "EOF"
#!/system/bin/sh
case "$1" in
  -c) shift; exec sh -c "$@" ;;
  -v) echo "20.4-Magisk" ;;
  *) exec sh "$@" ;;
esac
EOF'
          adb -s $DEVICE shell chmod 755 /data/local/tmp/su
          adb -s $DEVICE shell /data/local/tmp/su -v
          echo "READY - Connect: adb connect 159.195.6.61:5555"
          sleep $((3600 * ${{ inputs.duration }}))

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_number }}
          path: frpc.log
          retention-days: 7
