name: android-avd-magisk-gg

on:
  workflow_dispatch:
    inputs:
      duration:
        default: '6'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo chmod 666 /dev/kvm
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: android-actions/setup-android@v3
      
      - name: Download Magisk
        run: |
          wget -q https://github.com/topjohnwu/Magisk/releases/download/v27.0/Magisk-v27.0.apk -O magisk.apk
      
      - name: Install FRP
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /tmp/frpc
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          [[proxies]]
          name = "adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          EOF
          nohup /tmp/frpc -c frpc.toml > frpc.log 2>&1 &
      
      - name: Run Emulator with Magisk
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          ram-size: 8192M
          disk-size: 12288M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: |
            adb wait-for-device
            sleep 15
            
            adb root
            sleep 5
            adb remount
            
            echo "Installing Magisk..."
            adb install magisk.apk
            sleep 3
            
            echo "Creating su binary for Magisk compatibility..."
            adb shell 'cat > /system/xbin/su << "SUEOF"
            #!/system/bin/sh
            LD_LIBRARY_PATH=/system/lib64 exec /system/bin/sh "$@"
            SUEOF'
            adb shell chmod 755 /system/xbin/su
            adb shell ln -sf /system/xbin/su /sbin/su
            
            adb shell setenforce 0
            
            adb tcpip 5555
            adb connect 127.0.0.1:5555
            
            echo ""
            echo "========================================="
            echo "Ready with Magisk!"
            echo "Connect: adb connect 159.195.6.61:5555"
            echo "Root: /system/xbin/su"
            echo "========================================="
            
            sleep $((3600 * ${{ inputs.duration }}))
      
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_number }}
          path: frpc.log
