name: cloud-desktop-ubuntu-novnc

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Desktop, VNC, noVNC
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tightvncserver wget git python3 python3-pip
          sudo apt-get install -y websockify x11vnc

          # Setup user password for VNC
          VNC_PASS="cloud123"
          mkdir -p ~/.vnc
          x11vnc -storepasswd $VNC_PASS ~/.vnc/passwd
          
          # Download and run noVNC (web VNC client)
          git clone https://github.com/novnc/noVNC.git
          git clone https://github.com/novnc/websockify.git noVNC/utils/websockify

      - name: Start Desktop, VNC & noVNC
        run: |
          # Start a virtual desktop on :1
          export DISPLAY=:1
          Xvfb :1 -screen 0 1280x720x24 &
          sleep 2

          # Start XFCE desktop on :1 using noVNC
          export DISPLAY=:1
          # Start VNC server
          x11vnc -display :1 -rfbauth ~/.vnc/passwd -forever -shared -bg -nopw -rfbport 5901
          # Start noVNC (websocket proxy for VNC)
          nohup ./noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 6080 &

          # Confirm it's running
          ps aux | grep -E "Xvfb|x11vnc|novnc"
          echo "noVNC running at http://localhost:6080/vnc.html"
          
      - name: Tunnel noVNC Port via FRP
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          cat > frpc.toml << 'EOF'
          serverAddr = "YOUR_VPS_IP"
          serverPort = 7000
          transport.protocol = "kcp"
          [[proxies]]
          name = "novnc"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 6080
          remotePort = 6080
          EOF
          nohup ./frp_0.58.1_linux_amd64/frpc -c frpc.toml > frpc.log 2>&1 &
          
          echo "Tunnel started for port 6080."
          echo "Access your desktop at: http://YOUR_VPS_IP:6080/vnc.html"
          
      - name: Sleep (Keep Runner Alive)
        run: |
          sleep 21600
