name: cloud-desktop-ubuntu-simple

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration in hours'
        required: true
        default: '6'

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Desktop & VNC
        run: |
          echo "Installing packages..."
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tightvncserver x11vnc wget git
          sudo apt-get install -y firefox
          
          # Setup VNC password
          VNC_PASS="cloud123"
          mkdir -p ~/.vnc
          echo "$VNC_PASS" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          echo "✅ Packages installed"

      - name: Start Xvfb
        run: |
          Xvfb :1 -screen 0 1920x1080x24 > /tmp/xvfb.log 2>&1 &
          sleep 3
          ps aux | grep Xvfb | grep -v grep
          echo "✅ Xvfb started"

      - name: Start XFCE
        run: |
          export DISPLAY=:1
          startxfce4 > /tmp/xfce.log 2>&1 &
          sleep 5
          echo "✅ XFCE started"

      - name: Start VNC Server
        run: |
          export DISPLAY=:1
          echo "Starting VNC on port 5901..."
          
          x11vnc -display :1 -rfbauth ~/.vnc/passwd -forever -shared -bg -nopw -rfbport 5901
          sleep 2
          
          ps aux | grep x11vnc | grep -v grep
          netstat -tln | grep 5901
          
          echo "✅ VNC server ready on port 5901"

      - name: Setup FRP Tunnel
        run: |
          echo "Setting up FRP tunnel..."
          
          # Download FRP
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          
          # Create FRP config - forward VNC directly, not noVNC
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          
          [[proxies]]
          name = "vnc-desktop"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5901
          remotePort = 5901
          EOF
          
          # Start FRP client
          nohup ./frp_0.58.1_linux_amd64/frpc -c frpc.toml > frpc.log 2>&1 &
          sleep 3
          
          ps aux | grep frpc | grep -v grep
          
          echo ""
          echo "=========================================="
          echo "✅ CLOUD DESKTOP READY!"
          echo "=========================================="
          echo ""
          echo "📱 Connect via VNC Viewer:"
          echo "   Server: 159.195.6.61:5901"
          echo "   Password: cloud123"
          echo ""
          echo "Or use browser noVNC:"
          echo "   1. Install noVNC on your phone"
          echo "   2. Connect to: 159.195.6.61:5901"
          echo ""
          echo "=========================================="

      - name: Keep Alive
        run: |
          DURATION=${{ github.event.inputs.duration || '6' }}
          SECONDS=$((DURATION * 3600))
          echo "Running for $DURATION hours ($SECONDS seconds)..."
          
          # Monitor services every 10 minutes
          for ((i=0; i<$((SECONDS/600)); i++)); do
            sleep 600
            echo "Still running... services: $(ps aux | grep -E 'Xvfb|x11vnc|frpc' | grep -v grep | wc -l)"
          done

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-logs
          path: |
            /tmp/xvfb.log
            /tmp/xfce.log
            frpc.log
          retention-days: 7
