name: android-x86-fixed

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session hours (max 6)'
        required: false
        default: '6'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Android SDK with ADB
        run: |
          echo "📥 Installing Android SDK platform-tools..."
          sudo apt-get update -qq
          sudo apt-get install -y android-sdk-platform-tools adb
          
          adb version
          echo "✅ ADB installed"
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo chmod 666 /dev/kvm
      
      - name: Free Maximum Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /opt/hostedtoolcache
          sudo docker image prune --all --force
      
      - name: Setup Android-x86
        run: |
          echo "📥 Downloading Android-x86 (pre-rooted)..."
          wget -q "https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86_64-9.0-r2.iso/download" -O android-x86.iso || \
          wget -q "https://osdn.net/projects/android-x86/downloads/69704/android-x86_64-9.0-r2.iso" -O android-x86.iso
          
          sudo apt-get install -y qemu-kvm qemu-system-x86 qemu-utils
          qemu-img create -f qcow2 android-disk.qcow2 20G
      
      - name: Install FRP
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /usr/local/bin/
          
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          [[proxies]]
          name = "adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          EOF
          
          nohup frpc -c frpc.toml > frpc.log 2>&1 &
          pgrep frpc && echo "✅ FRP running"
      
      - name: Run Android-x86 MAX SPECS
        run: |
          echo ""
          echo "========================================="
          echo "🚀 Starting Android-x86 (MAX SPECS)"
          echo "========================================="
          echo ""
          
          sudo qemu-system-x86_64 \
            -enable-kvm \
            -m 12288 \
            -smp 4 \
            -cpu host \
            -device virtio-net-pci,netdev=net0 \
            -netdev user,id=net0,hostfwd=tcp::5555-:5555 \
            -cdrom android-x86.iso \
            -drive file=android-disk.qcow2,if=virtio,cache=writeback \
            -boot d \
            -vga virtio \
            -display none \
            -audiodev none,id=noaudio \
            -no-reboot &
          
          echo "⏳ Booting Android-x86 (120 seconds)..."
          sleep 120
          
          echo "📱 Connecting ADB..."
          adb connect 127.0.0.1:5555
          sleep 10
          
          adb devices
          
          echo ""
          echo "========================================="
          echo "✅ Android-x86 Running (Pre-Rooted!)"
          echo ""
          echo "💾 RAM: 12GB"
          echo "⚙️  CPU: 4 cores"
          echo "💿 Disk: 20GB"
          echo "🔓 Root: Built-in (no setup)"
          echo ""
          echo "📱 Connect: adb connect 159.195.6.61:5555"
          echo "🎮 Install GG: adb install GameGuardian.apk"
          echo "========================================="
          echo ""
          
          HOURS=${{ inputs.duration }}
          SECS=$((3600 * HOURS))
          START=$(date +%s)
          
          echo "Running for ${HOURS} hours..."
          
          ITER=0
          while true; do
            NOW=$(date +%s)
            ELAPSED=$((NOW - START))
            [ $ELAPSED -ge $SECS ] && break
            
            REMAIN=$((SECS - ELAPSED))
            H=$((REMAIN / 3600))
            M=$(((REMAIN % 3600) / 60))
            
            ITER=$((ITER + 1))
            [ $((ITER % 300)) -eq 0 ] && echo "[$(date '+%H:%M:%S')] ${H}h ${M}m left"
            
            sleep 1
          done
          
          echo "✅ Session complete"
      
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_number }}
          path: frpc.log
          retention-days: 7
