name: android-x86-prerooted

on:
  workflow_dispatch:
    inputs:
      duration:
        default: '6'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Android-x86
        run: |
          echo "📥 Downloading Android-x86 (pre-rooted)..."
          wget -q "https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86_64-9.0-r2.iso" -O android-x86.iso
          
          # Install QEMU
          sudo apt-get update
          sudo apt-get install -y qemu-kvm qemu-system-x86
          
          # Create virtual disk
          qemu-img create -f qcow2 android-disk.qcow2 8G
      
      - name: Install FRP
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /usr/local/bin/
          
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          [[proxies]]
          name = "adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          EOF
          
          nohup frpc -c frpc.toml > frpc.log 2>&1 &
      
      - name: Run Android-x86
        run: |
          qemu-system-x86_64 \
            -enable-kvm \
            -m 4096 \
            -smp 2 \
            -cpu host \
            -net nic \
            -net user,hostfwd=tcp::5555-:5555 \
            -cdrom android-x86.iso \
            -hda android-disk.qcow2 \
            -boot d \
            -display none &
          
          sleep 60
          adb connect 127.0.0.1:5555
          
          echo "✅ Android-x86 is pre-rooted!"
          echo "Connect: adb connect 159.195.6.61:5555"
          
          sleep $((3600 * ${{ inputs.duration }}))
